### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PY2'

### ISSUE THREAD

**Issue by mateuszbrylski** [ajenti/ajenti#891] opened 2016-02-26 21:35 UTC
Hi!

I have a problem with the last Update of Ajenti. After I updated Ajenti this error coming up:

Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 109, in <module>
    ajenti.config.load()
  File "/usr/lib/pymodules/python2.7/reconfigure/configs/base.py", line 42, in load
    (six.PY2 and isinstance(self.content, str)):
AttributeError: 'module' object has no attribute 'PY2'

**Comment by Xefir** [comment] 2016-02-26 21:51
What's your Python's version ?

**Comment by mateuszbrylski** [comment] 2016-02-26 21:53
2.7.10

**Comment by mateuszbrylski** [comment] 2016-02-28 13:45
Sorry i did a mistake the right version is: 2.7.3

**Comment by emmilive** [comment] 2016-02-28 15:13
Same here, Python Version 2.7.3

**Comment by Xefir** [comment] 2016-02-28 15:23
Sorry, my first question is incomplete : 

Above Python's version, what's your operating system and version ?
If possible, what's your installed python's eggs ? (`sudo pip list`)

I'm still looking into it, but with poor connectivity right now

**Comment by mateuszbrylski** [comment] 2016-02-28 15:27
Python: 2.7.3
Debian 7.9

I do not use pip

**Comment by Xefir** [comment] 2016-02-28 15:38
Find it ! To fix it, install the missing python-six package `sudo aptitude install python-six`

I open a PR for next installs :) 

https://github.com/Eugeny/reconfigure/issues/16

**Comment by mateuszbrylski** [comment] 2016-02-28 15:45
I did it but it doesn't works. I have the same error as before

**Comment by Xefir** [comment] 2016-02-28 15:47
Do you have restart the ajenti's service after installing the missing package ?

`sudo service ajenti restart`

**Comment by mateuszbrylski** [comment] 2016-02-28 15:47
Yes

**Comment by mateuszbrylski** [comment] 2016-02-28 15:48
xxx@webserver:~# service ajenti restart 
Stopping Ajenti:
[FAIL] not running ... failed!
Starting Ajenti:
28.02.2016 16:47 INFO  Using config file /etc/ajenti/config.json
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 109, in <module>
    ajenti.config.load()
  File "/usr/lib/pymodules/python2.7/reconfigure/configs/base.py", line 42, in load
    (six.PY2 and isinstance(self.content, str)):
AttributeError: 'module' object has no attribute 'PY2'
[FAIL] failed ... failed!

**Comment by Xefir** [comment] 2016-02-28 15:50
Okay :<

Can you install pip `sudo aptitude install python-pip` and give me the list of your eggs ?
`sudo pip list`

Thank you

**Comment by mateuszbrylski** [comment] 2016-02-28 15:52
Mako==0.7.0
MarkupSafe==0.15
PIL==1.1.7
SOAPpy==0.12.0
ajenti==1.2.23.7
argparse==1.2.1
chardet==2.0.1
distribute==0.6.24dev-r0
fpconst==0.7.2
gevent==0.13.6
gevent-socketio==0.3.6
gevent-websocket==0.3.6
greenlet==0.4.0
lockfile==0.8
lxml==2.3.2
medusa==0.5.4
meld3==0.6.5
oauthlib==0.1.2
passlib==1.5.3
psutil==0.6.1
pycrypto==2.6
python-apt==0.8.8.2
python-catcher==0.1.7
python-daemon==1.5.5
python-debian==0.1.21
python-debianbts==1.11
python-exconsole==0.1.5
python-ldap==2.4.10
reconfigure==0.1.75
reportbug==6.4.4
requests==0.12.1
six==1.1.0
supervisor==3.0a8
wsgiref==0.1.2

**Comment by Xefir** [comment] 2016-02-28 16:00
Waw, the installed six package is really, really old.

It sucks, because the PY2 identifier is available in this old build.

I will think about this issue for a better way.

For your specific problem, please upgrade your six package like so : `sudo pip install -U six`

**Comment by mateuszbrylski** [comment] 2016-02-28 16:03
It works now! Thank You!

**Comment by emmilive** [comment] 2016-02-28 16:19
Thanks @Xefir !

**Comment by Xefir** [comment] 2016-02-28 20:17
Okay, I got a universal solution that doesn't require six. It's on this PR : https://github.com/Eugeny/reconfigure/pull/17

Sorry for the inconvenances

**Comment by Xefir** [comment] 2016-02-29 17:15
The PR has been accepted. If the problem is fixed, can you please close this issue ? :)

**Closed as completed** 2016-11-09 13:22 UTC
